[package]
name = "transvoxel"
version = "0.1.0"
authors = ["Seb E. <seb@nospam.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Implementation of Eric Lengyel's Transvoxel Algorithm"
repository = "https://github.com/Gnurfos/transvoxel_rs"
categories = ["algorithms", "game-development", "graphics"]
keywords = ["gamedev", "graphics", "voxel", "transvoxel", "marching-cubes", "isosurface", "3d"]

[badges]
maintenance = { status = "experimental" }

[features]
default = ["serde"]
bevy_mesh = ["bevy", "bytemuck"]

[dependencies]
flagset = "*"
num = "*"
transvoxel-data = "*"
serde = { version = "1.0", optional = true, features = ["derive"] }
bevy = { version = "0.5.0", optional = true }
bytemuck = { version = "*", optional = true }


[dev-dependencies]
hamcrest = "*"
ndarray = "*"
bevy = { version = "0.5.0", features = ["dynamic"] }
bevy_fly_camera = { git = "https://github.com/Gnurfos/bevy_fly_camera", branch = "all" }
bevy_egui = "0.4.2"
bevy_screen_diags = "0.2.0"
noise = "0.7.0"
rand = "0.8.3"

[profile.dev]
opt-level = 3

[[example]]
name = "single_block"
required-features = ["bevy_mesh"]

[[example]]
name = "transition_across_blocks"
required-features = ["bevy_mesh"]
